#!/bin/sh

# autotools-scripts: Template project of autotools for scripts
# copyright (C) Assaf Gordon <assafgordon@gmail.com>
# License: MIT
# See: https://github.com/agordon/autotools-scripts

## This macro will be replaced with a warning:
##   @autogenerated_warning@
##   @autogenerated_timestamp@

# Variables defined in configure.ac
VERSION='@VERSION@'
PACKAGE_NAME='@PACKAGE_NAME@'
PACKAGE_BUGREPORT='@PACKAGE_BUGREPORT@'
PACKAGE_URL='@PACKAGE_URL@'
PACKAGE='@PACKAGE@'

# Variables set by user running ./configure
# (NOTE: use double-quotes as these will need parameter expansion)
prefix='@prefix@'                 # e.g. /usr/local
exec_prefix="@exec_prefix@"       # machine-dependant (usually same as prefix)
datarootdir="@datarootdir@"       # e.g. /usr/local/share
datadir="@datadir@"               # same as datarootdir (unless customized by user)
pkgdatadir="@datadir@/@PACKAGE@"  # e.g. /usr/local/share/PACKAGE/

libdir="@libdir@"                 # e.g /usr/local/lib
pkglibdir="@libdir@/@PACKAGE@"    #     /usr/local/lib/PACKAGE/
libexecdir="@libexecdir@"         # e.g. /usr/local/libexec
pkgexeclibdir="@libexecdir@/@PACKAGE@" # /usr/local/libexec/PACKAGE


# Another way of getting the data directory,
# This variable is explictly substituted in 'configure.ac'
DATADIR='@DATADIR@'

# This variable is defined in 'configure.ac',
# enabled with './configure --enable-foobar'.
foobar='@foobar@'

# Example files are expected to be installed here
# (see Makefile.am for corresponding installation)
exampledir="$DATADIR/examples"

datafile="$exampledir/data.txt"

die()
{
    BASE=$(basename "$0")
    echo "$BASE: error: $@" >&2
    exit 1
}

show_version_and_exit()
{
    echo "@PACKAGE_NAME@ - @VERSION@"
    echo "License: MIT"
    exit 0
}

show_help_and_exit()
{
    BASE=$(basename "$0")
    echo "@PACKAGE_NAME@ - Autotools+Scripts Demo program

Usage: $BASE [OPTIONS] FILE ...

FILE - File to process (in this demo, just print the file name)

Options:
    -h        = This help screen.
    -v        = be verbose
    -V        = print version.

Website: @PACKAGE_URL@
bug-reports/questions: @PACKAGE_BUGREPORT@

"

    exit
}

# Default values for parameters
show_usage=
show_version=
verbose=
# Parse parameters
while getopts Vvh param
do
    case $param in
    h)   show_help=1;;
    v)   verbose=1;;
    V)   show_version=1;;
    ?)   die "unknown command line option";;
    esac
done
shift $(($OPTIND - 1))

# Validate parameters
test -n "$show_help" && show_help_and_exit
test -n "$show_version" && show_version_and_exit
test -z "$1" && die "missing file name. See -h for help"

# This is set during './configure' with --enable-foobar
if test "x$foobar" = xtrue ; then
    echo "Foobar is Enabled"
else
    echo "Skipping Foobar (disabled in ./configure)"
fi

## Process each file
while test $# -gt 0 ; do
    filename="$1"
    shift 1

    echo "processing file '$filename'..."
done
