#!/bin/sh

# autotools-scripts: Template project of autotools for scripts
# copyright (C) Assaf Gordon <assafgordon@gmail.com>
# License: MIT
# See: https://github.com/autotools-scripts

mkdir -p m4
autoreconf -if
