#!/bin/sh

## This macro will be replaced with a warning:
##   @autogenerated_warning@
##   @autogenerated_timestamp@

# Variables defined in configure.ac
VERSION='@VERSION@'
PACKAGE_NAME='@PACKAGE_NAME@'
PACKAGE_TARNAME='@PACKAGE_TARNAME@'
PACKAGE_VERSION='@PACKAGE_VERSION@'
PACKAGE_STRING='@PACKAGE_STRING@'
PACKAGE_BUGREPORT='@PACKAGE_BUGREPORT@'
PACKAGE_URL='@PACKAGE_URL@'
PACKAGE='@PACKAGE@'

# Variables set by user running ./configure
# (NOTE: use double-quotes as these will need parameter expansion)
prefix='@prefix@'                 # e.g. /usr/local
exec_prefix="@exec_prefix@"       # machine-dependant (usually same as prefix)
datarootdir="@datarootdir@"       # e.g. /usr/local/share
datadir="@datadir@"               # same as datarootdir (unless customized by user)
pkgdatadir="@datadir@/@PACKAGE@"  # e.g. /usr/local/share/PACKAGE/

libdir="@libdir@"                 # e.g /usr/local/lib
pkglibdir="@libdir@/@PACKAGE@"    #     /usr/local/lib/PACKAGE/
libexecdir="@libexecdir@"         # e.g. /usr/local/libexec
pkgexeclibdir="@libexecdir@/@PACKAGE@" # /usr/local/libexec/PACKAGE


# Another way of getting the data directory,
# This variable is explictly substituted in 'configure.ac'
DATADIR='@DATADIR@'

# This variable is defined in 'configure.ac',
# enabled with './configure --enable-foobar'.
foobar='@foobar@'

# Example files are expected to be installed here
# (see Makefile.am for corresponding installation)
exampledir="$pkgdatadir/examples"

datafile="$exampledir/data.txt"

echo "Hello from version $VERSION"
echo "example file = $datafile"

if test "x$foobar" = xtrue ; then
    echo "Foobar is Enabled"
else
    echo "Skipping Foobar (disabled in ./configure)"
fi
